# Generated by Django 3.1.7 on 2021-02-23 23:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cliente', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Atendimento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vagas', models.IntegerField()),
                ('tipo', models.CharField(max_length=60, verbose_name='Tipo de Atendimento')),
                ('data', models.DateTimeField()),
                ('valor', models.CharField(max_length=60, verbose_name='Valor do Atendimento')),
                ('polo', models.CharField(max_length=60, verbose_name='Polo de Atendimento')),
                ('termo', models.TextField(help_text='Informe nesse campo todas as condições que o cliente deve aceitar para o atendimento', verbose_name='termo de Aceite')),
                ('supervisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-data'],
            },
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(auto_now=True)),
                ('confirmado', models.BooleanField(default=False)),
                ('atendimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='atendimento.atendimento')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='cliente.cliente')),
            ],
        ),
    ]
