# Generated by Django 3.1.7 on 2021-02-24 03:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polo', '0001_initial'),
        ('atendimento', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atendimento',
            name='polo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polo.polo'),
        ),
    ]
