# Generated by Django 3.1.7 on 2021-02-24 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atendimento', '0002_auto_20210224_0048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atendimento',
            name='polo',
            field=models.CharField(max_length=60, verbose_name='Polo de Atendimento'),
        ),
    ]
