# Generated by Django 3.1.7 on 2021-02-24 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('atendimento', '0004_auto_20210224_0100'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='atendimento',
            options={'ordering': ['-data'], 'verbose_name': 'Atendimento', 'verbose_name_plural': 'Atendimentos'},
        ),
        migrations.AlterModelOptions(
            name='reserva',
            options={'ordering': ['cliente'], 'verbose_name': 'Reserva', 'verbose_name_plural': 'Reservas'},
        ),
        migrations.AlterModelTable(
            name='atendimento',
            table='Atendimento',
        ),
        migrations.AlterModelTable(
            name='reserva',
            table='Reserva',
        ),
    ]
