# Generated by Django 3.1.7 on 2021-02-23 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=60, verbose_name='Nome')),
                ('telefone', models.CharField(help_text='Informe o telefone com Whatszapp', max_length=17, verbose_name='Telefone')),
            ],
            options={
                'db_table': 'Cliente',
                'ordering': ['nome'],
            },
        ),
    ]
