# Generated by Django 3.1.7 on 2021-02-24 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polo', '0002_polo_unidade'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='polo',
            options={'ordering': ['polo'], 'verbose_name': 'Polo', 'verbose_name_plural': 'Polos'},
        ),
    ]
